# git commands
alias ga='git add'
alias gaa='git add -A'
alias gb='git branch'
alias gbd='git branch -d'
alias gc='git commit -m'
alias gch='git checkout'
alias gchb='git checkout -b'
alias gcl='git clone'
alias gcli='git config -l'
alias gd='git diff'
alias gi='git init'
alias gl='git log'
alias glo='git log --oneline'
alias gls='git log --summary'
alias gm='git merge'
alias gmm='git merge master'
alias gpl='git pull origin'
alias gplm='git pull origin master'
alias gpod='git push origin --delete'
alias gps='git push origin'
alias gpsm='git push origin master'
alias gr='git restore'
alias grao='git remote add origin'
alias grh='git reset HEAD'
alias grs='git restore --staged'
alias grso='git remote set-url origin'
alias grv='git remote -v'
alias gs='git status'
alias gst='git stash'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gname='git config --global user.name'
alias gemail='git config --global user.email'

# ls commands
alias la='ls -A'
alias ll='ls -l'
alias lal='ls -lA'
alias lla='ls -lA'

# cd commands
alias cd..='cd ..'
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'

# find commands
alias findd='find . -type d'
alias findf='find . -type f'
alias findn='find . -name'
alias findrd='find / -type d'
alias findrf='find / -type f'
alias findrn='find / -name'

# mkdir commands
alias mkdirp='mkdir -p'
alias mkdirpv='mkdir -pv'

# chmod commands
alias c777='chmod -R 777'
alias c755='chmod -R 755'
alias c744='chmod -R 744'
alias c700='chmod -R 700'
alias c555='chmod -R 555'
alias c544='chmod -R 544'
alias c500='chmod -R 500'
alias c444='chmod -R 444'
alias c400='chmod -R 400'

# tar commands
alias untar='tar xf'
alias untargz='tar xzf'
alias targz='tar czf'
alias untarbz2='tar xjf'
alias tarbz2='tar cjf'

# zip commands
alias zipdm='zip -d *.zip __MACOSX/\*'
alias zipdd='zip -d *.zip \*/.DS_Store'

# history commands
alias h='history'
alias h10='history -10'
alias h20='history -20'
alias h30='history -30'
alias h40='history -40'
alias h50='history -50'
alias hg='history | grep'

# head and tail commands
alias head5='head -5'
alias head20='head -20'
alias tail5='tail -5'
alias tail20='tail -20'

# du commands
alias duc='du -c'
alias duch='du -hc'
alias duh='du -h'
alias duhc='du -hc'
alias duhs='du -hs'
alias dus='du -s'
alias dush='du -hs'

# python venv commands
alias pcvenv='python -m venv env'
alias pavenv='source env/bin/activate'
alias pdvenv='deactivate'

# brew commands (macOS only)
alias bcu='brew cask upgrade'
alias bi='brew install'
alias bl='brew list'
alias bri='brew reinstall'
alias bu='brew update'
alias bui='brew uninstall'
alias bup='brew upgrade'
alias nbi='HOMEBREW_NO_AUTO_UPDATE=1 brew install'

# mvn commands
alias mc='mvn clean'
alias mccp='mvn clean compile'
alias mci='mvn clean install'
alias mcp='mvn compile'
alias mcpk='mvn clean package'
alias mct='mvn clean test'
alias mdp='mvn deploy'
alias mdt='mvn dependency:tree'
alias mi='mvn install'
alias mpk='mvn package'

# docker commands
alias d='docker'
alias dcdown='docker compose down'
alias dcp='docker cp'
alias dcpull='docker compose pull'
alias dcup='docker compose up -d'
alias dbt='docker build -t'
alias dex='docker exec -it'
aliad dexd='docker exec -itd'
alias di='docker image'
alias dil='docker image ls'
alias dip='docker image prune'
alias dis='docker image ls'
alias dn='docker network'
alias dnl='docker network ls'
alias dnp='docker network prune'
alias dns='docker network ls'
alias dpl='docker pull'
alias dps='docker push'
alias dtag='docker tag'
alias dv='docker volume'
alias dvl='docker volume ls'
alias dvp='docker volume prune'
alias dvs='docker volume ls'

# kubectl commands
alias k='kubectl'
source <(kubectl completion bash | sed s/kubectl/k/g)

# vagrant commands
alias vbl='vagrant box list'
alias vbx='vagrant box'
alias vdt='vagrant destroy'
alias vhalt='vagrant halt'
alias vpg='vagrant plugin'
alias vpl='vagrant plugin list'
alias vpv='vagrant provision'
alias vrl='vagrant reload'
alias vrs='vagrant resume'
alias vssh='vagrant ssh'
alias vsp='vagrant suspend'
alias vst='vagrant status'
alias vup='vagrant up'

# miscellaneous
alias c='clear'
alias cpr='cp -r'
alias n='nano'
alias now='date "+%T %Z %A %x"'
alias p='python'
alias p2='python2'
alias p3='python3'
alias s='scala'
alias scpr='scp -r'
alias showpath='echo -e ${PATH//:/\\n}'
alias t='touch'
alias v='vim'
alias wh='which'
alias year='cal -y'

# modify .bashrc and .bash_profile
alias nanobr='sudo nano ~/.bashrc'
alias nanobp='sudo nano ~/.bash_profile'
